security:
    providers:
        in_memory:
            memory:
                users:
                    admin:  { password: %adminpass%, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:   ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
        default:
            anonymous: ~
    access_control:
        - { path: ^/shopadmin/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
